FROM {{ baseimage }}
MAINTAINER Matwey V. Kornilov <matwey.kornilov@gmail.com>

{% for v in env %}
ENV {{ v.key }} {{ v.value }}
{% endfor %}

{% for r in repos %}
RUN zypper -n ar '{{ r.value }}'
{% endfor %}

RUN zypper -n --gpg-auto-import-keys install --no-recommends --auto-agree-with-licenses --force-resolution {{ packages|join(' ') }}
